import React from 'react'

export default [
    {
        id: 1,
        img: "https://d4y1bmgncyek9.cloudfront.net/uploads/activity/images/2191/large_b9737356-9b26-420a-b5a9-b29dcba9d74e.jpg",
        title: "Moomin Park Welcomes Visitors to a Whimsical Wonderland in Saitama",
        text: "Saitama Prefecture is buzzing with excitement as 'Moomin' Park officially opens its gates to the public, inviting visitors to immerse themselves in the enchanting world of the Moomins. Nestled amidst the picturesque landscapes of Saitama City, this whimsical park brings to life the beloved characters and stories of Tove Jansson's iconic Moomin series.Since its grand opening, 'Moomin' Park has been delighting guests of all ages with its charming attractions, colorful scenery, and playful ambiance. Families, fans, and adventurers alike are flocking to the park to experience the magic of Moominvalley firsthand. At the heart of 'Moomin' Park stands the iconic Moomin House, a faithful recreation of the cozy dwelling that serves as the centerpiece of Moomintroll's adventures. Visitors can explore the charming interiors of the Moomin House, interact with costumed characters, and embark on a journey through the whimsical world of the Moomins.",
        date: "23rd October 2022"
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/3408354/pexels-photo-3408354.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        title: "Mount Fuji Hikes Gain Popularity as Outdoor Enthusiasts Flock to Japan",
        text: "As the allure of outdoor adventures continues to captivate travelers worldwide, Mount Fuji hikes are emerging as a premier destination for thrill-seekers and nature lovers alike. Nestled majestically in Japan's Honshu Island, Mount Fuji stands as an iconic symbol of Japan's natural beauty and cultural heritage. In recent years, there has been a notable surge in the number of visitors embarking on the challenge of scaling Mount Fuji's legendary peaks. This increase in popularity can be attributed to a combination of factors, including growing interest in outdoor activities, improved accessibility, and a desire to experience Japan's breathtaking landscapes firsthand. One of the most enticing aspects of Mount Fuji hikes is the sense of adventure and accomplishment that comes with conquering Japan's highest peak. Rising to an impressive height of 3,776 meters (12,389 feet), Mount Fuji offers a formidable yet rewarding challenge for hikers of all skill levels. From seasoned mountaineers seeking a rigorous ascent to casual adventurers looking to soak in panoramic views, there is something for everyone on Mount Fuji's trails. The official climbing season for Mount Fuji typically runs from early July to early September, coinciding with the warmer months when the mountain is free from snow and ice. During this time, hikers from around the world flock to the Fuji Five Lakes region, eager to embark on the arduous journey to the summit.",
        date: "14th April 2024"
    },
    {
        id: 3,
        img: "https://static1.straitstimes.com.sg/s3fs-public/styles/large30x20/public/articles/2022/08/29/ac_nintendoworld_290822.jpg?VersionId=Rs4rEBQEBOlk2PoyId6C_bms8A_JsXa5",
        title: "Super Mario World Debuts at Universal Studios Osaka, Delighting Fans Worldwide",
        text: "In a momentous occasion for gaming enthusiasts and theme park lovers alike, Universal Studios Japan in Osaka has unveiled its highly anticipated Super Mario World. This immersive attraction promises to transport visitors into the beloved universe of Nintendo's iconic plumber, Mario.The grand opening ceremony, held earlier today, marked the culmination of years of collaboration between Universal Parks & Resorts and Nintendo. As the gates swung open, fans from around the globe flooded into the vibrant world inspired by the classic video game series. Super Mario World offers an array of attractions and experiences designed to thrill fans of all ages. From thrilling rides to interactive exhibits, visitors have the chance to step into Mario's shoes and embark on unforgettable adventures. One of the main highlights of the park is the life-sized recreation of Peach's Castle, a central landmark in the Super Mario series. Guests can explore the castle grounds, interact with familiar characters, and even take on Bowser's challenges in an epic showdown. For adrenaline seekers, the park features exhilarating rides such as the Mario Kart Experience, where riders can race against each other in a high-speed battle through iconic Mario Kart courses. With cutting-edge technology and immersive storytelling, this attraction promises to be a highlight for thrill-seekers and gaming enthusiasts alike.But the fun doesn't stop there. Visitors can also immerse themselves in the colorful world of Yoshi's Adventure, a family-friendly ride that takes guests on a gentle journey through lush landscapes inspired by the Yoshi series. In addition to the rides, Super Mario World offers a variety of shops and dining options where guests can purchase exclusive merchandise and indulge in themed treats inspired by their favorite characters. The opening of Super Mario World represents a significant milestone for both Universal Studios Japan and Nintendo, showcasing the enduring appeal of the Mario franchise and its ability to captivate audiences across generations. As fans flock to experience the magic of Super Mario World, Universal Studios Osaka is poised to become a must-visit destination for gamers and theme park enthusiasts from around the world. With its blend of cutting-edge technology, immersive storytelling, and nostalgic charm, this new attraction is sure to leave a lasting impression on all who venture into its colorful world.",
        date: "5th January 2023"
    }
]